licensing:
  disallowed:
    - AGPL-1.0-only
    - AGPL-1.0-or-later
    - AGPL-3.0-only
    - AGPL-3.0-or-later
    - AGPL-1.0
    - AGPL-3.0
    - CC-BY-NC-ND-1.0
    - CC-BY-NC-ND-2.0
    - CC-BY-NC-ND-2.5
    - CC-BY-NC-ND-3.0
    - CC-BY-NC-ND-4.0
    - CC-BY-NC-SA-1.0
    - CC-BY-NC-SA-2.0
    - CC-BY-NC-SA-2.5
    - CC-BY-NC-SA-3.0
    - CC-BY-NC-SA-4.0
    - CC-BY-SA-1.0
    - CC-BY-SA-2.0
    - CC-BY-SA-2.5
    - CC-BY-SA-3.0
    - CC-BY-SA-4.0
    - GPL-1.0-only
    - GPL-1.0-or-later
    - GPL-2.0-only
    - GPL-2.0-or-later
    - GPL-3.0-only
    - GPL-3.0-or-later
    - SSPL-1.0
    - Sleepycat
    - Facebook