# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
executors:
  node14:
    docker:
      - image: cimg/node:18.14
    working_directory: ~/repo

orbs:
  codecov: codecov/codecov@3.2.4

commands:
  setup:
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Installing Dependencies
          command: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

jobs:
  build:
    executor: node14
    steps:
      - setup
      # run tests!
      - run: npm run test-ci
      - codecov/upload
      - store_test_results:
          path: junit
      - store_artifacts:
          path: junit

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
