name: Semantic Release
on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - run: npm install
      - run: git config --global user.email "test@project-helix.io" && git config --global user.name "Test Build"
      - run: npm test
        env:
          CIRCLE_REPOSITORY_URL: dummy-url

  build_win:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - run: npm install
      - run: git config --global user.email "test@project-helix.io" && git config --global user.name "Test Build"
      - run: npm test
        env:
          CIRCLE_REPOSITORY_URL: dummy-url

  release:
    runs-on: ubuntu-latest
    needs: [build, build_win]
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - run: npm install
      - run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
